GamesPortal/urls.py
from ckeditor_uploader.views import upload, browse
from django.views.decorators.cache import never_cache
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import LogoutView, LoginView, PasswordResetView, EmailVerificationSentView



# переопределим представления из allauth для того, чтобы прописать наши стили в шаблоны
class MyLogoutView(LogoutView):
    template_name = 'registration/logout.html'  # копия шаблога из allauth, только с нашим default.html. Ниже такие же операции


class MyLoginView(LoginView):
    template_name = 'registration/login.html'


class MyPasswordResetView(PasswordResetView):
    template_name = 'registration/password_change.html'


class MyEmailVerificationSentView(EmailVerificationSentView):
    template_name = 'registration/verification_sent.html'


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # подключаем встроенные эндопинты для работы с локализацией
    path('ckeditor/upload/', upload, name='ckeditor_upload'),
    path(r'ckeditor/browse/', never_cache(browse), name='ckeditor_browse'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('', lambda request: redirect('board/', permanent=False)),
    path("board/", include("board.urls"), name='board'),
    # блок переопределенных
    path('accounts/login/', MyLoginView.as_view(), name='account_login'),
    path('accounts/logout/', MyLogoutView.as_view(), name='account_logout'),
    path('accounts/email/', MyPasswordResetView.as_view(), name='account_reset_password'),
    path('accounts/confirm-email/', MyPasswordResetView.as_view(), name='account_email_verification_sent'),
    path("accounts/", include("allauth.urls")),  # регистрация будет через allauth
    path("accounts/", include("accounts.urls")),  # а здесь работа с кастомным профилем
    path("board/", include("board.urls"), name='board'),
]

board/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import PostsList, PostDetail, PostCreate, PostUpdate, PostDelete, ResponseCreate, \
    ResponseDelete, ResponseDetail, ResponsesList, response_approve, UserPosts

urlpatterns = [
    # список объявлений
    path('', PostsList.as_view(), name='posts_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/response/create/', ResponseCreate.as_view(), name='response_add'), # отозваться на объявление
    path('response/<int:pk>', ResponseDetail.as_view(), name='response'),
    path('response/<int:pk>/delete/', ResponseDelete.as_view(), name='response_delete'),
    path('response/<int:pk>/approve/', response_approve, name='response_accept'),
    # приватный список откликов на объявления пользователя
    path('response_list/', ResponsesList.as_view(), name='response_list'),
    # список объявлений пользователя в профиле - доступен и публично
    path('user_posts/<int:pk>', UserPosts.as_view(), name='user_posts'),
    ]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor.fields import RichTextField


# автор объявления или отклика
class Author(models.Model):
    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    full_name = models.CharField(max_length=255, verbose_name='ФИО')
    author = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Автор')
    is_subscriber = models.BooleanField(verbose_name='Подписчик', default=False)

    def __str__(self):
        if self.full_name:
            return f'{self.full_name}'
        else:
            return str(self.author)


# категория объявления
class Category(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    TYPE = ['Танки',
            'Хилы',
            'ДД',
            'Торговцы',
            'Гилдмастеры',
            'Квестгиверы',
            'Кузнецы',
            'Кожевники',
            'Зельевары',
            'Мастера заклинаний',
            ]
    name = models.CharField(max_length=20,
                            help_text='Категории объявлений',
                            verbose_name='Категория', unique=True)

    def __str__(self):
        return self.name


# объявление
class Post(models.Model):
    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = RichTextField(config_name='default')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    attach = models.FileField(upload_to='uploads/%Y/%m/%d/', blank=True, null=True, verbose_name='Вложение')

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


# отклик на объявление
class Response(models.Model):
    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Объявление')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text[0:30]}'

board/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post, Response


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='default'))
    class Meta:
        model = Post
        fields = [
            'title',
            'category',
            'content',
            'attach',
        ]
        labels = {'title': ('Заголовок'),
                  'content': (''),
                  'category': ('Категория'),
                  'attach': ('Вложение'),
                  }
        """
        widgets = {'attach': forms.FileInput(
                attrs={'class': 'form-control'},
            ),
        }
        """

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('text',)
        labels = {'text': (''),
                  }

board/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime, timedelta
from django.contrib.auth.models import User, AnonymousUser

from .models import Post, Response
from .forms import PostForm, ResponseForm
from .models import Author
from GamesPortal.settings import DAILY_POST_LIMIT

class PostsList(ListView):
    queryset = Post.objects.all()
    ordering = '-created'
    template_name = 'board/posts_list.html'
    context_object_name = 'posts'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        prev_day = datetime.utcnow() - timedelta(days=1)
        # количество постов с этого момента
        user = self.request.user
        if not isinstance(self.request.user, AnonymousUser):
            posts_day_count = posts_day_count = Post.objects.filter(created__gte=prev_day, author__author=user).count()
            context['allow_post'] = (posts_day_count < DAILY_POST_LIMIT)
        else:
            context['allow_post'] = False
        context['posts_amount'] = len(self.queryset)
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'board/post.html'
    context_object_name = 'post'

class PostCreate(LoginRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = 'board/post_edit.html'

    paginate_by = 10

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        user = request.user
        if form.is_valid():
            print(f' selected file {request.FILES}')
            post = form.save(commit=False)
            post.author = Author.objects.get_or_create(author=user)[0]
            post.save()
            return self.form_valid(form)
        return redirect('/')


# Добавляем представление для изменения публикации.
class PostUpdate(LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'board/post_edit.html'


# Представление удаляющее публикацию
class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'board/post_delete.html'
    success_url = reverse_lazy('posts_list')


class ResponseCreate(LoginRequiredMixin, CreateView):
    model = Response
    form_class = ResponseForm
    template_name = 'board/response_add.html'

    success_url = '/board/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = User.objects.get(id=self.request.user.id)
        self.object.post = Post.objects.get(id=self.kwargs.get('pk'))
        self.object.save()
        return super().form_valid(form)


class ResponseDetail(LoginRequiredMixin, UpdateView):
    model = Response
    form_class = ResponseForm
    template_name = 'board/response.html'
    context_object_name = 'post'


def response_approve(request, pk):
    obj = Response.objects.get(id=pk)
    obj.accepted = True
    obj.save()
    return redirect('response_list')

# Представление удаляющее отклик
class ResponseDelete(LoginRequiredMixin, DeleteView):
    model = Response
    template_name = 'board/response_delete.html'
    success_url = reverse_lazy('response_list')


class ResponsesList(LoginRequiredMixin, ListView):
    ordering = '-created'
    template_name = 'board/response_list.html'
    context_object_name = 'posts'

    paginate_by = 10  # вот так мы можем указать количество записей на странице

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['posts_amount'] = len(context['posts'])
        return context

    def get_queryset(self):
        user = self.request.user
        queryset = Response.objects.filter(post__author__author=user)
        return queryset


class UserPosts(ListView):
    queryset = Post.objects.all()
    ordering = '-created'
    template_name = 'board/user_posts.html'
    context_object_name = 'posts'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['posts_amount'] = len(context['posts'])
        return context

    def get_queryset(self):
        user = self.kwargs.get('pk')
        queryset = Post.objects.filter(author__author=user)
        return queryset

templates/board/index.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}

<!-- Название у нас будет Post -->
{% block title %}
<!-- на самом деле бессмысленно, если в default не задать блок  -->
Post
<!-- но если задать, то текст вылезает вверху страницы, а не в виде принятого title  -->
{% endblock title %}

<!-- В контенте на странице мы выводим саму новость, идентификатор которой был передан в url -->
{% block content %}
<h1> {{ content }} </h1>
{% endblock content %}

templates/board/post.html
{% extends 'default.html' %}
{% load static %}
<script type="text/javascript" src='{% static "ckeditor/ckeditor-init.js" %}'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/ckeditor.js" %}'></script>
{% block title %}
{% endblock title %}

{% block content %}
<br>
<h3 style="text-align: left;">{{ post.title }}</h3>
<p style="text-align: left;"> {{post.created|date:'d.m.Y'}}&nbsp;в категории {{ post.category }} &nbsp;&nbsp;&nbsp;
    Автор&nbsp;<a href="{% url 'profile' pk=post.author.author.id %}">{{ post.author }}</a></p>
<br>
<div style="text-align: left;">
    {{post.content|safe}}
</div>

{% if post.author.author != user %}
<form form enctype="multipart/form-data" method="post" action="{% url 'response_add' pk=post.pk %}">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <div class="modal-footer">
        <button class="btn btn-outline-primary" type="submit">Ответить на объявление</button>
    </div>
</form>
{% endif %}
{% endblock content %}

templates/board/post_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем новость "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/board/post_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Объявление</h1>
<hr>


<form action="" method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>

{% endblock content %}

templates/board/posts_list.html
{# наследуемся от шаблона default.html #}
{% extends 'default.html' %}

{% load custom_tags %}
{% block title %}
Объявления
{% endblock title %}

{% block content %}
<h1 style="text-align: left;">Все объявления на {{ time_now|date:'d.m.Y' }} (всего {{posts_amount}})
    {% if request.user.is_authenticated and allow_post %}
    <a href="{% url 'post_create' %}"> Подать объявление </a>
    {% endif %}
</h1>


{% if posts %}
<table cellspacing="0" cellpadding="3"> <!-- Начинаем описывать таблицу -->
    <thead>
    <tr>
        <th>
            Заголовок
        </th>
        <th>
            Дата
        </th>
        <th>
            Категория
        </th>
        <th>
            Автор
        </th>
        <th>
            Текст
        </th>
        {# Условие получается составным. #}
        {% if perms.board.change_post or perms.board.delete_post %}
        <th>Действия</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>

    {% for post in posts %}
    <tr>
        <td style="text-align: left;"><a href="{% url 'post_detail' pk=post.id %}">{{ post.title|truncatewords:8 }}</a>
        </td>
        <td style="text-align: left;">{{ post.created|date:'d.m.Y' }}</td>
        <td style="text-align: center;">{{ post.category }}</td>
        <td style="text-align: left;"><a href="{% url 'profile' pk=post.author.author.id %}">{{ post.author }}</a></td>
        <td style="text-align: left;">{{ post.content|safe|truncatewords:20 }}</td>
        <td>
            {# проверим право на редактирование поста #}
            {% if request.user.is_authenticated and request.user == post.author.author %}
            <a href="{% url 'post_update' pk=post.id %}">Редактировать</a>
            <a href="{% url 'post_delete' pk=post.id %}">Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h2>Объявления не найдены!</h2>
{% endif %}
<br>
{% if not request.user.is_authenticated %}
<p> Авторизуйтесь, чтобы подать объявление </p>
{% elif not allow_post %}
<p> Сегодня вы исчерпали лимит объявлений :( </p>
{% endif %}
{# Добавляем пагинацию на страницу #}
{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?{% url_replace page=1 %}">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}
{% endblock content %}

templates/board/response.html
{% extends 'default.html' %}

{% block content %}
<h1>Отклик на объявление</h1>
<hr>

<p style="text-align: left;"> {{post.post.created|date:'d.m.Y'}}&nbsp;в категории {{ post.post.category }} &nbsp;
    было опубликовано объявление <a href="{% url 'post_detail' pk=post.post.id %}">{{ post.post.title }}</a>

<hr>
<p style="text-align: left;"> {{ post.user }} написал: </p>
<div style="text-align: left;">
    {{post.text}}
</div>

{% if not post.accepted %}
<button class="btn btn-outline-primary" type="submit"><a href="{% url 'response_accept' pk=post.id %}">Принять отзыв</a></button>
{% else %}
<button class="btn btn-outline-primary" type="submit"><a href="{% url 'response_list' %}">Назад</a></button>
{% endif %}
{% endblock content %}

templates/board/response_add.html
{% extends 'default.html' %}

{% block content %}
<h1>Отклик на объявление</h1>
<hr>


<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-outline-primary" type="submit" value="Save"/>
</form>
<button class="btn btn-outline-primary" type="submit"><a href={% url 'posts_list' %}> Отменить</a></button>

{% endblock content %}

templates/board/response_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление отклика</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем отклик "{{ object.text }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/board/response_list.html
{# наследуемся от шаблона default.html #}
{% extends 'default.html' %}

{% load custom_tags %}
{% block title %}
Отклики на объявления
{% endblock title %}

{% block content %}
<h1 style="text-align: left;">Все отклики на {{ time_now|date:'d.m.Y' }} (всего {{posts_amount}})</h1>

{% if posts %}
<table cellspacing="0" cellpadding="3">
    <thead>
    <tr>
        <th>
            Дата
        </th>
        <th>
            Отозвался
        </th>
        <th>
            Отклик
        </th>
        <th>На объявление</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>

    {% for post in posts %}
    <tr>
        <td style="text-align: left;">{{ post.created|date:'d.m.Y' }}</td>
        <td style="text-align: left;">{{ post.user }}</td>

        <td style="text-align: left;"><a href="{% url 'response' pk=post.id %}">{{ post.text|truncatewords:20 }}</a></td>

        <td style="text-align: left;">{{ post.post.title|truncatewords:10 }}</td>
        <td>
            {# проверим право на редактирование поста #}
            {% if request.user.is_authenticated and request.user == post.post.author.author %}
            <a href="{% url 'response_delete' pk=post.id %}">Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h2>Откликов нет</h2>
{% endif %}
<br>

<a href="?{% url_replace page=1 %}">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% if page_obj.has_next %}
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}
{% endblock content %}

templates/board/user_posts.html
{# наследуемся от шаблона default.html #}
{% extends 'default.html' %}

{% load custom_tags %}
{% block title %}
Объявления
{% endblock title %}

{% block content %}
<h1 style="text-align: left;">Все объявления на {{ time_now|date:'d.m.Y' }} (всего {{posts_amount}})
</h1>

{% if posts %}
<table cellspacing="0" cellpadding="3">
    <thead>
    <tr>
        <th>
            Заголовок
        </th>
        <th>
            Дата
        </th>
        <th>
            Категория
        </th>
        <th>
            Автор
        </th>
        <th>
            Текст
        </th>
    </tr>
    </thead>
    <tbody>

    {% for post in posts %}
    <tr>
        <td style="text-align: left;"><a href="{% url 'post_detail' pk=post.id %}">{{ post.title|truncatewords:8 }}</a>
        </td>
        <td style="text-align: left;">{{ post.created|date:'d.m.Y' }}</td>
        <td style="text-align: center;">{{ post.category }}</td>
        <td style="text-align: left;"><a href="{% url 'profile' pk=post.author.author.id %}">{{ post.author }}</a></td>
        <td style="text-align: left;">{{ post.content|truncatewords:20 }}</td>


    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h2>Объявления не найдены!</h2>
{% endif %}
<br>


{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?{% url_replace page=1 %}">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}
{% endblock content %}